services:
    CodeBuds\GenerateTsBundle\Service\FileInformationService:
        public: false
    codebuds.generate_ts.file_information_service:
        alias: CodeBuds\GenerateTsBundle\Service\FileInformationService

    CodeBuds\GenerateTsBundle\Command\GenerateTsInterfacesCommand:
        tags:
            - { name: console.command }
        arguments:
            $namespace: '%generate_ts.namespace%'
            $inputDirectory: '%generate_ts.input_directory%'
            $outputDirectory: '%generate_ts.output_directory%'
            $fileInformationService: '@codebuds.generate_ts.file_information_service'
